#1
thisdict={
"brand":"ford",
"model":"mustang",
"year":564
}
print(len(thisdict))
print("**********")
#2
thisdict={
"brand":"ford",
"model":"mustang",
"year":564
}
thisdict["color"]="blue"
print(thisdict)
print("**********")
#3
thisdict={
"brand":"ford",
"model":"mustang",
"year":564
}
thisdict.pop("model")
print(thisdict)
print("**********")
#4
thisdict={
"brand":"ford",
"model":"mustang",
"year":564
}
thisdict.popitem()
print(thisdict)
print("**********")
thisdict={
"brand":"ford",
"model":"mustang",
"year":564
}
del thisdict["model"]
print(thisdict)
print("**********")
#5
thisdict={
"brand":"ford",
"model":"mustang",
"year":564
}
del thisdict
print(thisdict)
print("**********")
#6
thisdict={
"brand":"ford",
"model":"mustang",
"year":564
}
thisdict.clear()
print(thisdict)
print("**********")