#1
thisset={"Areej","Nouf","Fateamah"}
print(len(thisset))
print("************")
#2
thisset={"Areej","Nouf","Fateamah"}
thisset.remove("Fateamah")
print(thisset)
print("************")
#3
thisset={"Areej","Nouf","Fateamah"}
x=thisset.pop()
print(x)
print(thisset)
print("************")
#4
thisset={"Areej","Nouf","Fateamah"}
thisset.clear()
print(thisset)
print("************")
#5
thisset={"Areej","Nouf","Fateamah"}
del thisset
print(thisset)
print("************")
#6
thisset=set(("Areej","Nouf","Fateamah"))
print(thisset)
print("************")
#7
